my-argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.1
  dex:
    enabled: false
  server:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx 
      enabled: true 
      tls: false
      selfSigned: false
    ingressGrpc:
      annotations:
        kubernetes.io/ingress.class: nginx 
      enabled: true 
      tls: false
      selfSigned: false    
    insecure: true    
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
 